export const USER_LOGIN = 'USER_LOGIN';

export const FETCH_CURR_CODE = 'FETCH_CURRENCIES_CODE';

export const ADD_EXPENSES = 'ADD_EXPENSES';

export const REMOVE_EXPENSES = 'REMOVE_EXPENSES';

export const EDIT_EXPENSES = 'EDIT_EXPENSES';

export const UPDATE_EXPENSES = 'UPDATE_EXPENSES';
